csl
=======

```{r echo=FALSE}
library("knitr")
hook_output <- knitr::knit_hooks$get("output")
knitr::knit_hooks$set(output = function(x, options) {
   lines <- options$output.lines
   if (is.null(lines)) {
     return(hook_output(x, options))  # pass to default hook
   }
   x <- unlist(strsplit(x, "\n"))
   more <- "..."
   if (length(lines)==1) {        # first n lines
     if (length(x) > lines) {
       # truncate the output, but add ....
       x <- c(head(x, lines), more)
     }
   } else {
     x <- c(if (abs(lines[1])>1) more else NULL, 
            x[lines], 
            if (length(x)>lines[abs(length(lines))]) more else NULL
           )
   }
   # paste these lines together
   x <- paste(c(x, ""), collapse = "\n")
   hook_output(x, options)
 })

knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE, 
  message = FALSE
)
```

`csl` is an R client for exploring CSL styles. 

This package is inspired by and steals ideas from the Ruby gem [csl](https://github.com/inukshuk/csl-ruby)

The [Citation Style Language 1.0.1 specification](http://citationstyles.org/downloads/specification.html)

## Install

```{r eval=FALSE}
install.packages("devtools")
devtools::install_github("sckott/csl")
```

```{r}
library("csl")
```

## Load CSL style from a URL

```{r}
jps <- style_load('http://zotero.org/styles/american-journal-of-political-science')
```

## Query style information

```{r output.lines = 1:10}
jps$info
```

```{r}
jps$title
```

```{r}
jps$citation_format
```

```{r}
jps$links_template
```

```{r output.lines = 1:10}
jps$editor
```

```{r output.lines = 1:10}
jps$author
```

## Get raw XML

```{r output.lines=1:10}
style_xml('http://zotero.org/styles/american-journal-of-political-science')
```

## Get styles

Get styles from the Github repo at [https://github.com/citation-style-language/styles-distribution](https://github.com/citation-style-language/styles-distribution)

```{r eval=FALSE}
get_styles()
#> 
#> Done! Files put in /Users/sacmac/styles
```

## Get locales

Get locales from the Github repo at [https://github.com/citation-style-language/locales](https://github.com/citation-style-language/locales)

```{r eval=FALSE}
get_locales()
#> 
#> Done! Files put in /Users/sacmac/locales
```
